include ../Makefile.tests_common

# other values supported are sx1262, sx1268 and llcc68
LORA_DRIVER ?= sx1262
USEMODULE += $(LORA_DRIVER)

USEMODULE += xtimer
USEMODULE += shell
USEMODULE += shell_cmds_default

include $(RIOTBASE)/Makefile.include
